### PR TITLE
Update Slack invite link

### PR DESCRIPTION
**Pull request by martint**

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]

**Comment by kenandominic** [comment]
hey @martint @ebyhr the link has expired yet again

**Comment by martint** [comment]
@kenandominic, thanks for the report. I've updated it.

**Comment by helmiazizm** [comment]
Hello @martint. Can you activate the link again? It appears that the one in Trino front page and the one you just gave has expired again. Thanks.

**Comment by martint** [comment]
We updated the one on the website yesterday. Is it still not working for you?

**Comment by helmiazizm** [comment]
Yeah, it was not working by the time I wrote the comment. The link is alive again right now. Thank you.

**Pull request merged**
