### PR TITLE
Update 2022-07-13-how-to-use-airflow-to-schedule-trino-jobs.md

### PR DESCRIPTION
**Pull request by cpard**
Added the missing HN link plus changed the html to open the links to a new tab instead of doing it at the current one.

### CODE REVIEW

**Comment by mosabua** [comment]
@brianzhan can you get the link updated in your redirector or should we have a mix here. In either case  I am fine but wont be around to drive merging this

**Comment by cpard** [comment]
> 

The link on the shortener is immutable, it won't let you update it

**Comment by mosabua** [comment]
Do we still need this to go live @cpard @brianzhan ?

**Comment by bitsondatadev** [comment]
Closing, this was already fixed.

**Pull request closed without merging**
