### PR TITLE
Add Development Containers

### PR DESCRIPTION
**Pull request by Emiller88**
Adds a [development container](https://containers.dev/), which should alleviate any M1 build issues of contributors. Also allows contributors to quickly set up an environment with [GitHub Codespaces](https://github.com/features/codespaces) for quick contributions.

### CODE REVIEW

**Comment by mosabua** [comment]
What M1 build issues. Since we updated the build works just fine and uses a multi-arch container

**Comment by mosabua** [comment]
> What M1 build issues are you referring to? Since we updated the version of sphinx recently, the build works just fine and uses a multi-arch container.

Sorry .. I misspoke .. this PR is for the website. We typically build with a native installation of Jekyll and have no performance issues. Using a docker container is actually slower. That said .. we could consider adding a docker setup, but we would probably use official jekyll images.

**Comment by Emiller88** [comment]
> What M1 build issues are you referring to? 
Sorry, it was actually an error with netlify-cli, I couldn't get it to reproduce on a second machine.

> That said .. we could consider adding a docker setup, but we would probably use official jekyll images.
To clear up, this isn't a replacement for the netlify builds, and contributors can still use a local ruby installation with jekyll. This is just another option to skip the manual setup and just "Open in dev container"

**Comment by hashhar** [comment]
Alternatives that people aren't actively using break without notice and actually create work.

**Comment by Emiller88** [comment]
>Alternatives that people aren't actively using break without notice and actually create work.

That's fine, up to you all whether you want to maintain it or not. We've found them to be really popular in our nf-core repos, and it lowers the barrier to entry for people to contribute.

The only line that wasn't auto generated from the [Jekyll template](https://containers.dev/templates) is the last line in the post-install
```
npm install netlify-cli -g
```

**Comment by bitsondatadev** [comment]
Hey thanks, @Emiller88! It's a pretty neat idea for sure. I like that it would lower the barrier to entry for contributing blogs. Let me noodle on this one with @mosabua and the maintainers.

As @hashhar mentioned we have to scrutinize new frameworks as we run pretty thin in this project, but if it opens up opportunities for folks to contribute I don't want to skip it.

**Comment by hashhar** [comment]
Thanks for bringing up the good point about ease of contributing blogs @bitsondatadev. I hadn't considered that.

If it is actively used and won't lead to worse experience for contributors (because of occasionally being broken) then I would welcome this change.

**Comment by mosabua** [comment]
Looked at this a bit more, couple of questions: 

* I assume I can test this locally by checking out the branch and the using VS Code and whatever, correct? 
* Can I somehow test the codespaces thing?
* How can I set specific Jekyll versions or command line options like --future
* Can I use the official Jekyll docker containers instead (I have a shell script for that already anyway) or do I need to use the dev container one?
* Whats the advantage of using dev containers rather than a shell script and docker call ... seems like I need to install the devcontainer cli and such ..

**Comment by Emiller88** [comment]
>     * I assume I can test this locally by checking out the branch and the using VS Code and whatever, correct?
Yep exactly! [Dev container tutorial.](https://code.visualstudio.com/docs/devcontainers/tutorial)
>     * Can I somehow test the codespaces thing?
[Docs ](https://docs.github.com/en/codespaces/getting-started/quickstart) to demo it, I think you may need to enable it on this repo?
>     * How can I set specific Jekyll versions or command line options like --future
That's a good question, I'm not sure on the Jekyll versions. The command line option, you can run whatever you want inside of the container version. 
>     * Can I use the official Jekyll docker containers instead (I have a shell script for that already anyway) or do I need to use the dev container one?
I'm not exactly sure if there's anything inside the container that's VS Code specific. You can have a Dockerfile in the directory as well and build from that, so you could probably use the official image.
>     * Whats the advantage of using dev containers rather than a shell script and docker call ... seems like I need to install the devcontainer cli and such ..
Probably removing those as a barrier to entry for new contributors.

You don't need to install anything with codespaces, and the VS Code setup is simple, [the only requirement is docker from what I can tell](https://code.visualstudio.com/docs/devcontainers/containers#_getting-started). 

As an aside, It looks like you can use [k8s](https://code.visualstudio.com/remote/advancedcontainers/use-docker-kubernetes), so it might make a nice addition to trino-getting-started since you're looking to use the helm chart 🤔

**Pull request closed without merging**
