### PR TITLE
Add Trino Summit banner

### PR DESCRIPTION
**Pull request by kylefraser**
This PR adds a banner to the homepage for the Trino Summit.

Chatted with @bitsondatadev on creating a simple, eye-catching banner.

Screen Shot 2021-08-10 at 10 19 41 AM

### CODE REVIEW

**Comment by bitsondatadev** [comment]
Great job @kylefraser! This looks good!

**Review by mosabua — CHANGES_REQUESTED** [review]
Given that this will be up for many months, do we want to make it scream a little less and take a little less room?

**Comment by bitsondatadev** [comment]
> it signals we have things going on

When did I become such a marketer.

**Comment by kylefraser** [comment]
I agree it could be a bit thinner.

The orange in the gradient _should_ be our orange variable on top and then a darker orange on the bottom. 

Here are a couple of other examples with different colors. I also thinned out the banner from 320px -> 240px. Things may be slightly off center, but that would be fixed in code. 

can always go back to drawing board too. 

<details>
<summary>screenshots</summary>


Screen Shot 2021-05-07 at 6 55 57 AM

Screen Shot 2021-05-07 at 6 55 16 AM

Screen Shot 2021-05-07 at 6 53 08 AM

Screen Shot 2021-05-07 at 6 51 47 AM

Screen Shot 2021-05-07 at 6 50 31 AM

Screen Shot 2021-05-07 at 6 50 12 AM

Screen Shot 2021-05-07 at 6 49 57 AM

Screen Shot 2021-05-07 at 6 45 38 AM


</details>

**Comment by bitsondatadev** [comment]
image

This is my vote. The darker button + waving Commander makes it scream less IMO and if we just add a very slight dark gradient coming up from the bottom it will tame the scream the little bit more.

**Comment by bitsondatadev** [comment]
@mosabua how does this look now?

**Comment by mosabua** [comment]
Personally I prefer the dark one .. the orange just screams too much. If we go with orange I would make it thinner..

**Comment by mosabua** [comment]
We should probably get this live soon

**Comment by bitsondatadev** [comment]
Is it ready to go?

**Comment by kylefraser** [comment]
Good to go! Updated screenshot

**Comment by bitsondatadev** [comment]
> @bitsondatadev
> Good to go! Updated screenshot

Thanks @kylefraser, one last thing, we should remove the Hosted By Starburst. People will see that the event is hosted by Starburst on the registration page.

**Review by mosabua — APPROVED** [review]
Lets get this live asap ..

**Pull request merged**
