### PR TITLE
Add Cube to resources

### PR DESCRIPTION
**Pull request by igorlukanin**

### CODE REVIEW

**Comment by igorlukanin** [comment]
@bitsondatadev I did! 😄 

Screenshot 2022-11-21 at 21 59 20

**Comment by hashhar** [comment]
@cla-bot check

**Review by bitsondatadev — CHANGES_REQUESTED** [review]

**Comment by bitsondatadev** [comment]
> @bitsondatadev I did! 😄

thanks :)

**Comment by mosabua** [comment]
We can merge this as it stands. We are in the process of changing the whole tools and integrations stuff and will probably need to reach out when that becomes more real.

**Comment by mosabua** [comment]
Are you okay with us merging this @igorlukanin ?

**Pull request merged**
