### PR TITLE
Using Logo Trino-ko-tiny in Readme.md

### PR DESCRIPTION
**Pull request by raihan71**
Using logo trino-ko-tiny in readme  file made looks nicer

<strong>Before</strong>
image

<strong>After</strong>
image

### CODE REVIEW

**Comment by mosabua** [comment]
Works for me +1

**Comment by raihan71** [comment]
> Works for me +1

can we make this to ```hacktoberfest``` repo?

**Comment by bitsondatadev** [comment]
Hey @raihan71 I'm sorry to be getting on this so late. We haven't participated in hacktoberfest before. What do we have to do to get you credit for hacktoberfest?

**Comment by raihan71** [comment]
> Hey @raihan71 I'm sorry to be getting on this so late. We haven't participated in hacktoberfest before. What do we have to do to get you credit for hacktoberfest?

hey man, no worries! I'm happy to contribute even though it tiny changes haha, sorry late reply

**Comment by raihan71** [comment]
> Hey @raihan71 I'm sorry to be getting on this so late. We haven't participated in hacktoberfest before. What do we have to do to get you credit for hacktoberfest?

hey @bitsondatadev I would take my credit hacktoberfest by inviting you to my podcast, let's talk about open-source and your journey to become a developer :)

**Comment by monimiller** [comment]
Hey @raihan71, I dropped an email to the hacktoberfest team to see if we can get you any credit. Got the info on how to participate as maintainers on hacktoberfest so hopefully we can participate in 2022!

**Comment by bitsondatadev** [comment]
Thanks for grabbing this @monimiller!

**Comment by raihan71** [comment]
> Hey @raihan71, I dropped an email to the hacktoberfest team to see if we can get you any credit. I also got the info on how we can potentially participate in 2022!

oh thank you so much @monimiller can't wait for the prize!

**Comment by raihan71** [comment]
> Thanks for grabbing this @monimiller!

thanks again man @bitsondatadev

**Pull request merged**
