### PR TITLE
Updates to the user logos grids

### PR DESCRIPTION
**Pull request by kylefraser**
This PR updates the responsive styles for the user logos grid. It uses responsive techniques that allow the client to choose a smaller image, to optimize mobile loading speeds. Also includes an `img` fallback. 

Logos were also compressed without losing fidelity. 

<details>
<summary>Snapshots</summary>

Screen Shot 2021-02-23 at 9 53 54 AM

Screen Shot 2021-02-22 at 4 33 40 PM

</details>

### CODE REVIEW

**Comment by mosabua** [comment]
@martint @dain and @electrum 

The approach in this PR was decided as a very good first improvement for the user testimonial by @aliloney @kylefraser and myself. It improves the site in terms of page load to be incremental and the experience for mobile users. It allows us to retain showing all logos, and in the future more logos, without any randomization. 

Please review and merge this as soon as convenient. 

We will still pursue the randomized selection, with a client side JS approach probably, as a second wave of improving the setup, but would like to get this live now.

**Review by mosabua — APPROVED** [review]
Looks good. Nice and clean.

**Comment by mosabua** [comment]
@kylefraser did you submit the CLA yet? It would be good to get this merged soon.

**Comment by kylefraser** [comment]
> @kylefraser did you submit the CLA yet? It would be good to get this merged soon.

Yes, I sent it out to cla@trino.io yesterday around 10am.

**Comment by electrum** [comment]
Looks great!

**Comment by electrum** [comment]
We don't need a CLA for the website, but thanks for sending it

**Pull request merged**
