### PR TITLE
Add data source logos

### PR DESCRIPTION
**Pull request by ryandoowan**

### CODE REVIEW

**Review by mosabua — CHANGES_REQUESTED** [review]
A couple of changes:

* Ensure that all logos go either to the vertical or horizontal edge and are as big as possible within the image (e.g. MySQL, Redis , Pinot and other logos are too small)
* Please confirm that all images use 72dpi
* Change all filenames to be lowercase only

**Review by mosabua — COMMENTED** [review]
Can you make sure the line on top and bottom of the TPC logo is the same thickness..

**Comment by ryandoowan** [comment]
> Can you make sure the line on top and bottom of the TPC logo is the same thickness..

**Review by mosabua — APPROVED** [review]
Looks great now .. lets merge and see how they all show up in context.

**Pull request merged**
