### PR TITLE
Add simple HTML redirect for star

### PR DESCRIPTION
**Pull request by mosabua**

### CODE REVIEW

**Comment by electrum** [comment]
I'm not sure this is needed, but see discussion on #178

**Comment by mosabua** [comment]
This was requested by @bitsondatadev and @martint .. its nice to have this for local testing at least.

**Comment by electrum** [comment]
For local testing, we should update our development instructions to use [Netlify Dev](https://www.netlify.com/products/dev/):
```
brew install netlify-cli
netlify dev
```
This starts Jekyll locally, but also starts a Netlify server that proxies through it and handles the Netlify config, so things like our documentation proxying will work correctly.

**Comment by electrum** [comment]
This should not be needed after #189

**Pull request closed without merging**
