### PR TITLE
Add BestSecret user entry

### PR DESCRIPTION
**Pull request by mosabua**

### CODE REVIEW

**Comment by mosabua** [comment]
Is this okay @alaturqua ?

**Comment by alaturqua** [comment]
Looks good to me.

Would you add our tech blog as well?

[https://medium.com/bestsecret-tech](url)

**Comment by mosabua** [comment]
> https://medium.com/bestsecret-tech

I did not add since I think it would look bad .. there are now new posts since 2021

**Comment by mosabua** [comment]
> > https://medium.com/bestsecret-tech
> 
> I did not add since I think it would look bad .. there are no new posts since 2021

I had crossed eyes and only looked at the entry post .. added the link now ..

**Review by martint — APPROVED** [review]

**Pull request merged**
